### ISSUE TITLE
deconstructing objects

### ISSUE THREAD

**Issue by cjessett** [Gtichy/codecademy#1]
(Simplify) [Here](https://github.com/Gtichy/codecademy/blob/8d880d583aa19042835d3785d4a7b52ef6dc8a58/jammming/jammming/src/util/Spotify.js#L44-L47) instead of using `Object.entries` just call the property of the object. For example if the `jsonResponse` looks like this: 
```
{ "images":[{"height":null,"url":"https://fbcdn-profile-a.akamaihd.net/hprofile-ak-frc3/t1.0-1/1970403_10152215092574354_1798272330_n.jpg","width":null}],"product":"premium","type":"user","uri":"spotify:user:wizzler" }
```
Then you can access the url like so: `jsonResponse.images[0].url`.

**Comment by Gtichy** [comment]
Got it. I've made the update, and pushed the new code.
