### ISSUE TITLE
variables

### ISSUE THREAD

**Issue by cjessett** [Gtichy/codecademy#2]
(Simplify) [This](https://github.com/Gtichy/codecademy/blob/8d880d583aa19042835d3785d4a7b52ef6dc8a58/jammming/jammming/src/util/Spotify.js#L133) variable is unnecessary. If you would like to use a variable, you don't need a global variable declared with `let`, simply use `const userId = jsonResponse.id` within the function. However, you don't event need a variable, just `return jsonResponse.id` in the function.

**Comment by Gtichy** [comment]
Got it. Makes sense. I've made the update and pushed the code.
